### ISSUE TITLE
patch

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/HW-express#1]
https://github.com/Alex-it-work/HW-express/blob/1589590fa96da82e40443f5f34bf123400568679/models/message.js#L50
- на patch может приходить частичное оюновление, т.е. body будет содержать не все свойства, которые есть в сообщениях. Поэтому логичнее в обновленный месседж распределять старое содержимое плюс обновлять те поля, что пришли.

**Comment by Alex-it-work** [comment]
fixed
